---

- name: update host groups
  hosts: localhost
  pre_tasks:
  - name: refresh gce inventory
    command: '{{ inventory_dir }}/gce/hosts/gce.py --refresh-cache'
    changed_when: false
  - meta: refresh_inventory
  roles:
  - ./playbooks/roles/instance-groups

- hosts: localhost
  vars:
    glusterfs_nodes: "{{ groups['app_nodes'] }}"
    glusterfs_devices:
    - '/dev/disk/by-id/google-gluster'
    zone_to_number:
      asia-east1-a: 1
      asia-east1-b: 2
      asia-east1-c: 3
      asia-northeast1-a: 4
      asia-northeast1-b: 5
      asia-northeast1-c: 6
      asia-southeast1-a: 7
      asia-southeast1-b: 8
      australia-southeast1-a: 9
      australia-southeast1-b: 10
      australia-southeast1-c: 11
      europe-west1-b: 12
      europe-west1-c: 13
      europe-west1-d: 14
      europe-west2-a: 15
      europe-west2-b: 16
      europe-west2-c: 17
      us-central1-a: 18
      us-central1-b: 19
      us-central1-c: 20
      us-central1-f: 21
      us-east1-b: 22
      us-east1-c: 23
      us-east1-d: 24
      us-east4-a: 25
      us-east4-b: 26
      us-east4-c: 27
      us-west1-a: 28
      us-west1-b: 29
      us-west1-c: 30
  tasks:
  #- debug: var=hostvars[item]
  #  with_items: "{{ glusterfs_nodes }}"
  - name: Generate topology file
    template:
      src: "./topology.json.j2"
      dest: "../../topology.json"
